
"""publikasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSva-P3pFLbWi9VSWbVSynpcOdzMo6Md
"""

from google.colab import files
import os

folder = "/content/bps_publikasi_2024"
for filename in os.listdir(folder):
    files.download(os.path.join(folder, filename))

import requests
import os

API_KEY = "2ad01e6a21b015ea1ff8805ced02600c"
BASE_LIST_URL = "https://webapi.bps.go.id/v1/api/list/model/publication/lang/ind/domain/3500/page/{page}/year/2024/key/" + API_KEY
DETAIL_URL = "https://webapi.bps.go.id/v1/api/view/domain/3500/model/publication/lang/ind/id/{pub_id}/key/" + API_KEY

# Folder simpan PDF
os.makedirs("bps_publikasi_2024", exist_ok=True)

page = 1
while True:
    print(f"🔄 Fetching page {page}")
    resp = requests.get(BASE_LIST_URL.format(page=page)).json()
    data = resp.get("data")

    # Struktur data tidak sesuai atau sudah habis
    if not isinstance(data, list) or len(data) < 2:
        print("✅ Tidak ada data lagi. Selesai.")
        break

    publikasi_list = data[1]

    for pub in publikasi_list:
        pub_id = pub["pub_id"]
        title = pub["title"].replace("/", "-").replace("\\", "-").strip()

        # Ambil detail publikasi
        detail_resp = requests.get(DETAIL_URL.format(pub_id=pub_id)).json()
        pdf_url_encoded = detail_resp.get("data", {}).get("pdf")

        if pdf_url_encoded:
            pdf_url = pdf_url_encoded.replace("\\/", "/")
            print(f"📥 Downloading: {title}")
            try:
                pdf_resp = requests.get(pdf_url)
                with open(f"bps_publikasi_2024/{title}.pdf", "wb") as f:
                    f.write(pdf_resp.content)
            except Exception as e:
                print(f"❌ Gagal download {title}: {e}")

    page += 1
